baseURL = 'http://jrn.dev/'
languageCode = 'en-us'
title = 'Joseph Nash'

enableEmoji = false
enableRobotsTXT = true

[menu]

[[menu.main]]
name = "Download Resume"
identifier = "resume"
weight = 100
url = "resume/joseph-r-nash-resume.pdf"

[params]
title = 'Joseph Nash'
author = 'Joseph Nash'
description = 'Cleared Software Engineer'
profilePicture = 'images/profile.jpeg'

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/joseph-r-nash/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://www.github.com/jrn90"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:joe@jrn.dev"

[module]
[[module.imports]]
path = "github.com/lxndrblz/anatole"
disable = false
